import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';

export interface UefnProject {
  name: string;
  root: string;
  projectFile: string;
}

export async function detectUefnProject(): Promise<UefnProject | undefined> {
  const candidates = new Set<string>();

  // A .code-workspace generated by UEFN lives at the project root.
  const wsFile = vscode.workspace.workspaceFile;
  if (wsFile && wsFile.scheme === 'file') {
    candidates.add(path.dirname(wsFile.fsPath));
  }

  // Workspace folders may point inside the project (e.g. .../Test/Content) —
  // walk up a few levels to find the .uefnproject sibling.
  for (const folder of vscode.workspace.workspaceFolders ?? []) {
    let dir = folder.uri.fsPath;
    for (let i = 0; i < 6; i++) {
      candidates.add(dir);
      const parent = path.dirname(dir);
      if (parent === dir) break;
      dir = parent;
    }
  }

  for (const dir of candidates) {
    const entries = await fs.promises.readdir(dir).catch(() => [] as string[]);
    const projectFile = entries.find(f => f.toLowerCase().endsWith('.uefnproject'));
    if (projectFile) {
      return {
        name: path.basename(projectFile, path.extname(projectFile)),
        root: dir,
        projectFile: path.join(dir, projectFile),
      };
    }
  }
  return undefined;
}
