import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';

export interface UefnProject {
  name: string;
  root: string;
  projectFile: string;
}

export async function detectUefnProject(): Promise<UefnProject | undefined> {
  const ordered: string[] = [];
  const seen = new Set<string>();
  const add = (dir: string) => {
    if (!seen.has(dir)) {
      seen.add(dir);
      ordered.push(dir);
    }
  };

  // A .code-workspace generated by UEFN lives at the project root — check it first.
  const wsFile = vscode.workspace.workspaceFile;
  if (wsFile && wsFile.scheme === 'file') {
    add(path.dirname(wsFile.fsPath));
  }

  // Workspace folders may point inside the project (e.g. .../Test/Content) —
  // walk up a few levels to find the .uefnproject sibling.
  for (const folder of vscode.workspace.workspaceFolders ?? []) {
    let dir = folder.uri.fsPath;
    for (let i = 0; i < 6; i++) {
      add(dir);
      const parent = path.dirname(dir);
      if (parent === dir) break;
      dir = parent;
    }
  }

  // Fan out the readdir calls in parallel, then walk the results in priority order.
  const results = await Promise.all(
    ordered.map(dir => fs.promises.readdir(dir).catch(() => [] as string[])),
  );
  for (let i = 0; i < ordered.length; i++) {
    const projectFile = results[i].find(f => f.toLowerCase().endsWith('.uefnproject'));
    if (projectFile) {
      return {
        name: path.basename(projectFile, path.extname(projectFile)),
        root: ordered[i],
        projectFile: path.join(ordered[i], projectFile),
      };
    }
  }
  return undefined;
}
